version: '3.9'

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    container_name: create_certs
    command: >
      bash -c '
        if [[ ! -f /certs/bundle.zip ]]; then
          sudo bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          sudo unzip /certs/bundle.zip -d /certs;
        fi;
        sudo chown -R 1000:0 /certs;
      '
    working_dir: /usr/share/elasticsearch
    volumes:
      - certs:/certs
      - .:/usr/share/elasticsearch/config/certificates
    networks:
      - elastic
    ports:
      - 80:80
      - 443:443

volumes:
  certs:
    driver: local

networks:
  elastic:
    driver: bridge
