version: '3.9'

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    container_name: create_certs
    command: >
      sudo bash -c '
        mkdir -p /certs;
        chmod 777 /certs;
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem --self-signed --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs;
        fi;
        chown -R 1000:0 /certs;
      '
    working_dir: /usr/share/elasticsearch
    volumes:
      - certs:/certs
      - .:/usr/share/elasticsearch/config/certificates
    networks:
      - elastic
    ports:
      - 80:80
      - 443:443

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/azureuser/elastic-kibana-docker-nginx-letsencrypt/certs

networks:
  elastic:
    driver: bridge
